AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Node 22 ESM Lambda for Box get folder items using box-node-sdk v10 JWT

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 256
    Timeout: 30
    Architectures:
      - x86_64

Parameters:
  BoxJwtSecretArn:
    Type: String
    Default: ''
    Description: ARN or name of the Secrets Manager secret containing the Box JWT config JSON.

Conditions:
  HasBoxJwtSecretArn: !Not [!Equals [!Ref BoxJwtSecretArn, '']]

Resources:
  GetBoxFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-box-files
      CodeUri: .
      Handler: src/get-box-files.handler
      Policies:
        - !If
          - HasBoxJwtSecretArn
          - Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref BoxJwtSecretArn
          - !Ref AWS::NoValue
      Events:
        GetBoxFilesApi:
          Type: Api
          Properties:
            Path: /box/folders/{folderId}/items
            Method: get
      Environment:
        Variables:
          BOX_JWT_SECRET_ARN: !If [HasBoxJwtSecretArn, !Ref BoxJwtSecretArn, !Ref AWS::NoValue]
          BOX_CONFIG_FILE: ''
          BOX_FOLDER_ID: '0'
          BOX_JWT_CONFIG_JSON: ''
          BOX_JWT_CONFIG_JSON_BASE64: ''
          BOX_CLIENT_ID: ''
          BOX_CLIENT_SECRET: ''
          BOX_JWT_KEY_ID: ''
          BOX_PRIVATE_KEY: ''
          BOX_PRIVATE_KEY_PASSPHRASE: ''
          BOX_ENTERPRISE_ID: ''
          BOX_USER_ID: ''
          BOX_AS_USER_ID: ''

Outputs:
  GetBoxFilesApiUrl:
    Description: API endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/box/folders/{folderId}/items'
